services:
  - type: web
    name: mindtrace
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn MindTrace.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mindtrace-db
          property: connectionString

databases:
  - name: mindtrace-db
