# Generated by Django 5.1.7 on 2025-11-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='想做完成',
            field=models.BooleanField(default=False),
        ),
    ]
